# Generated by Django 5.2.1 on 2025-05-19 14:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('attribute_count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('use_count', models.PositiveIntegerField()),
                ('use_type', models.PositiveSmallIntegerField(choices=[(0, 'Amount off'), (1, 'Percent off')], default=0)),
                ('amount_off', models.DecimalField(decimal_places=3, max_digits=19, null=True)),
                ('percent_off', models.PositiveSmallIntegerField(null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('code', models.CharField(max_length=255)),
                ('ticket_ids', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attribute_category_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('select_type', models.PositiveSmallIntegerField(choices=[(0, 'No selection'), (1, 'Single'), (2, 'Multiple')], default=0)),
                ('input_type', models.IntegerField(choices=[(0, 'No entry'), (1, 'Manual'), (2, 'Select from list')], default=0)),
                ('input_list', models.TextField(blank=True, null=True)),
                ('attribute_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.attributecategory')),
            ],
        ),
        migrations.CreateModel(
            name='CouponHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(max_length=255)),
                ('redeemer_name', models.CharField(max_length=255)),
                ('order_sn', models.CharField(max_length=255, null=True)),
                ('use_time', models.DateTimeField(auto_now_add=True)),
                ('coupon_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.coupon')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.order')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('pic', models.TextField(blank=True)),
                ('album_pics', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Live'), (2, 'Started'), (3, 'Ended'), (4, 'Canceled')], default=0)),
                ('capacity', models.PositiveIntegerField()),
                ('is_free', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('publish_time', models.DateTimeField()),
                ('organizer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.event'),
        ),
        migrations.CreateModel(
            name='CheckoutSetting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(choices=[('AR', 'AR'), ('AT', 'AT'), ('AU', 'AU'), ('BE', 'BE'), ('BR', 'BR'), ('CA', 'CA'), ('CH', 'CH'), ('CL', 'CL'), ('CO', 'CO'), ('CY', 'CY'), ('CZ', 'CZ'), ('DE', 'DE'), ('DK', 'DK'), ('EE', 'EE'), ('ES', 'ES'), ('FI', 'FI'), ('FR', 'FR'), ('GB', 'GB'), ('GR', 'GR'), ('HK', 'HK'), ('HU', 'HU'), ('IE', 'IE'), ('IL', 'IL'), ('IT', 'IT'), ('JP', 'JP'), ('LT', 'LT'), ('LU', 'LU'), ('LV', 'LV'), ('MT', 'MT'), ('MX', 'MX'), ('MY', 'MY'), ('NL', 'NL'), ('NO', 'NO'), ('NZ', 'NZ'), ('PE', 'PE'), ('PH', 'PH'), ('PL', 'PL'), ('PT', 'PT'), ('SE', 'SE'), ('SG', 'SG'), ('SI', 'SI'), ('SK', 'SK'), ('TH', 'TH'), ('TW', 'TW'), ('US', 'US')], max_length=3)),
                ('currency_code', models.CharField(choices=[('ARS', 'ARS'), ('AUD', 'AUD'), ('BRL', 'BRL'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CZK', 'CZK'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('HKD', 'HKD'), ('HUF', 'HUF'), ('ILS', 'ILS'), ('JPY', 'JPY'), ('MXN', 'MXN'), ('MYR', 'MYR'), ('NOK', 'NOK'), ('NZD', 'NZD'), ('PHP', 'PHP'), ('PLN', 'PLN'), ('SEK', 'SEK'), ('SGD', 'SGD'), ('THB', 'THB'), ('TWD', 'TWD'), ('USD', 'USD')], max_length=3)),
                ('checkout_method', models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Offline'), (2, 'Payment system')], default=0)),
                ('offline_note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.event')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
                ('attribute_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.attributecategory')),
                ('attribute_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.attribute')),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.event')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('host_name', models.CharField(max_length=255)),
                ('sorting', models.FloatField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.event')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('sorting', models.FloatField()),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.event')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('pic', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=19)),
                ('capacity', models.PositiveIntegerField()),
                ('quantity_sold', models.PositiveIntegerField()),
                ('max_quantity_per_order', models.PositiveIntegerField()),
                ('sorting', models.FloatField()),
                ('is_free', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.event')),
            ],
        ),
        migrations.CreateModel(
            name='TicketStock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity_available', models.PositiveIntegerField()),
                ('quantity_lock', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('detail_address', models.TextField()),
                ('google_place_id', models.TextField()),
                ('latiude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))])),
                ('organizer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='venue_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.venue'),
        ),
    ]
