# Generated by Django 5.2.1 on 2025-05-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_sn', models.CharField(max_length=255, null=True)),
                ('owner_name', models.CharField(max_length=255, null=True)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=19)),
                ('pay_amount', models.DecimalField(decimal_places=3, max_digits=19)),
                ('coupon_amount', models.DecimalField(decimal_places=3, max_digits=19)),
                ('checkout_method', models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Offline'), (2, 'Payment system')], default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Started'), (2, 'Pending'), (3, 'Completed'), (4, 'Abandoned')], default=1)),
                ('delivery_method', models.PositiveSmallIntegerField(choices=[(0, 'Email'), (1, 'Phone')], default=0)),
                ('bill_receiver_email', models.CharField(max_length=255, null=True)),
                ('receiver_name', models.CharField(max_length=255, null=True)),
                ('payment_time', models.DateTimeField()),
                ('delivery_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAttendee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_sn', models.CharField(max_length=255, null=True)),
                ('ticket_name', models.CharField(max_length=255, null=True)),
                ('ticket_pic', models.TextField(blank=True)),
                ('ticket_price', models.DecimalField(decimal_places=3, max_digits=19)),
                ('ticket_quantity', models.PositiveIntegerField()),
                ('real_amount', models.DecimalField(decimal_places=3, max_digits=19)),
                ('coupon_amount', models.DecimalField(decimal_places=3, max_digits=19)),
                ('bill_receiver_email', models.CharField(max_length=255, null=True)),
                ('receiver_email', models.CharField(max_length=255, null=True)),
                ('refuned', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_name', models.CharField(max_length=255, null=True)),
                ('order_ticket_price', models.DecimalField(decimal_places=3, max_digits=19)),
                ('order_ticket_quantity', models.PositiveIntegerField()),
                ('real_amount', models.DecimalField(decimal_places=3, max_digits=19)),
                ('coupon_amount', models.DecimalField(decimal_places=3, max_digits=19)),
                ('refund_qty', models.PositiveIntegerField()),
                ('refund_amount', models.PositiveIntegerField()),
                ('qty_processed', models.PositiveIntegerField()),
                ('amount_rocessed', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_sn', models.CharField(max_length=255, null=True)),
                ('from_name', models.CharField(max_length=255, null=True)),
                ('from_email', models.CharField(max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('order_pay_amount', models.DecimalField(decimal_places=3, max_digits=19)),
                ('checkout_method', models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Offline'), (2, 'Payment system')], default=0)),
                ('delivery_method', models.PositiveSmallIntegerField(choices=[(0, 'Email'), (1, 'Phone')], default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Refunding'), (2, 'Processed'), (3, 'Rejected'), (4, 'Error')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
